name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.100-preview.5.23303.2

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build .\webApi\b3.Api\ --configuration Release

      - name: Run tests
        run: dotnet test .\webApi\B3.Domain.Test\ --no-build --verbosity normal --configuration Release
          
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"kleberribeiro89_b3" /o:"kleberribeiro89" /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a" /d:sonar.host.url="https://sonarcloud.io"
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a"
      
  