name: Build and Analyze

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.305
          
      - name: Restore dependencies
        run: dotnet restore .\webApi\b3.Api\
        
      - name: Build
        run: dotnet build .\webApi\b3.Api\ --configuration Release

      - name: Run tests
        run: dotnet test .\webApi\B3.Domain.Test\ 
        
      - name: Install SonarQube Scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarQube analysis
        run: dotnet sonarscanner begin /k:"kleberribeiro89_b3" /o:"kleberribeiro89" /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a" /d:sonar.host.url="https://sonarcloud.io"

      - name: Build and Analyze with SonarQube
        run: dotnet build .\webApi\b3.Api\ && dotnet sonarscanner end /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a"
          
      # - name: Build and analyze
        # env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # shell: powershell
        # run: |
          # .\.sonar\scanner\dotnet-sonarscanner begin /k:"kleberribeiro89_b3" /o:"kleberribeiro89" /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a" /d:sonar.host.url="https://sonarcloud.io"
          # dotnet --version
          # .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="8e50f722a630906acee4186524aee87b1d82c82a"
      
  